name: Artifact React App CI/CD

on:
  push:
    paths:
      - "react-app/**"
    branches: [main, develop]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16,18]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: node -v
      - run: echo "Running Node ${{ matrix.node }} on ${{ matrix.os }}"

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build
  
  test:
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16,18]
    runs-on: ${{ matrix.os }} 
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies and run tests
        run: npm test

    
